name: Build and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sncf-on-time:$GITHUB_SHA

    - name: Tag the Docker image
      run: docker tag sncf-on-time:$GITHUB_SHA europe-docker.pkg.dev/ensai-2023-373710/christophe/sncf-on-time:$GITHUB_SHA

    - name: Docker auth on GCP
      uses: docker/login-action@v2
      with:
        registry: europe-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Push the Docker tagged image
      run: docker push europe-docker.pkg.dev/ensai-2023-373710/christophe/sncf-on-time:$GITHUB_SHA

    - name: Auth GCP gcloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    #- name: Delete Cloud Run Job
    #    run: |
    #      gcloud --quiet beta run jobs delete christophe-sncf-on-time

    - name: Deploy Cloud Run Job
      run: |
        gcloud --quiet beta run jobs create christophe-sncf-on-time \
          --project ensai-2023-373710 \
          --region europe-west1 \
          --image europe-docker.pkg.dev/ensai-2023-373710/christophe/sncf-on-time:$GITHUB_SHA \
          --args ${{ secrets.TOKEN }},2023-01-05,Rennes \
          --set-env-vars SERVICE_ACCOUNT_INFO='${{ secrets.GOOGLE_CREDENTIALS }}'
